#include <iostream>
#include <fstream>
#include <string>
#include <ctime>

#include "model.h"

int gen_obj_from_heightmap(int** heightmap, int x, int y, float scale, std::string name){
	
	//open ObjFile
	std::ofstream objFile(name, std::ofstream::out | std::ofstream::trunc);

	if (!objFile.is_open()) {
		std::cerr << "Error opening file : " << name << "\n";
		return 1;
	}

	//a little bit of formalities
	std::time_t currentTime = std::time(nullptr);
	std::tm* localTime = std::localtime(&currentTime);
	objFile << "# Height map (live) conversion to obj \n# Model generated by an automatic function \n# Made by -- Neon \n# date : " << 
	localTime->tm_mday << " " << (localTime->tm_mon +1) << "-" << (localTime->tm_year + 1900) << "\n\n\n";


	objFile << "g ground\n";
	for(int i = 0; i < x; i++){
		for(int j = 0; j < y; j++){
			objFile << "v " << i << ".0 " << ((float)heightmap[i][j]/scale) << " " << j << ".0 \n";	
		}
	}

	for(int i = 0; i < x; i++ ){
		objFile << "\nl ";
		for(int j = 0; j < y; j++){
			objFile << ((i * y) + (j+1)) << " ";
		}
	}

	for(int j = 0; j < y; j++ ){
		objFile << "\nl ";
		for(int i = 0; i < x; i++){
			objFile << ((i * x) + (j+1)) << " ";		
		}
	} 

	return 0;
};

